swagger: "2.0"
info:
  description: "This service fetches defense news articles from a specific source and returns them in JSON format."
  version: "1.0.0"
  title: "Defense News Article Fetcher"
host: "localhost:5000"
basePath: "/"
schemes:
- "http"
paths:
  /get_news:
    get:
      summary: "Get news articles"
      description: "Returns a list of defense news articles, including headlines, image URLs, and article links."
      responses:
        200:
          description: "A list of news articles"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Article"
        500:
          description: "Error message"
          schema:
            $ref: "#/definitions/Error"
definitions:
  Article:
    type: "object"
    properties:
      headline:
        type: "string"
        example: "Example Headline of a News Article"
      image_url:
        type: "string"
        example: "http://example.com/image.jpg"
      article_link:
        type: "string"
        example: "http://example.com/article"
  Error:
    type: "object"
    properties:
      error:
        type: "string"
        example: "Failed to fetch articles"
